#!/bin/bash
#BSUB -J timing_init           
#BSUB -q hpc                   
#BSUB -W 10                       
#BSUB -R "rusage[mem=250MB]"
#BSUB -n 8                      
#BSUB -R "span[hosts=1]"          
#BSUB -o batch_outputs/timing_init_%J.out     
#BSUB -e batch_error_output/timing_init_%J.err     

source /dtu/projects/02613_2025/conda/conda_init.sh
conda activate 02613

python preliminary_hpc.py --time
